options:
  logging: CLOUD_LOGGING_ONLY
  machineType: E2_HIGHCPU_32
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '.', '-t', 'gcr.io/piccione-dev/website:$BUILD_ID']
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'gcr.io/piccione-dev/website:$BUILD_ID']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args:
    - run
    - deploy
    - piccione-dev
    - --image
    - gcr.io/piccione-dev/website:$BUILD_ID
    - --region
    - us-east1
  secretEnv:
    - BACKEND_API_TOKEN
availableSecrets:
  secretManager:
    - versionName: 'projects/piccione-dev/secrets/backend-api-token/versions/latest'
      env: 'BACKEND_API_TOKEN'
